import type { Metadata } from "next";
import "../styles/global.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` flex justify-between flex-col`}>
                <section className=" flex-1">{children}</section>
            </body>
        </html>
    );
}
